<?php

declare(strict_types=1);
use Illuminate\Database\Seeder;

class PermissionSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $items = [

            ['id' => 1, 'title' => 'user_management_access'],
            ['id' => 2, 'title' => 'permission_access'],
            ['id' => 3, 'title' => 'permission_create'],
            ['id' => 4, 'title' => 'permission_edit'],
            ['id' => 5, 'title' => 'permission_view'],
            ['id' => 6, 'title' => 'permission_delete'],
            ['id' => 7, 'title' => 'role_access'],
            ['id' => 8, 'title' => 'role_create'],
            ['id' => 9, 'title' => 'role_edit'],
            ['id' => 10, 'title' => 'role_view'],
            ['id' => 11, 'title' => 'role_delete'],
            ['id' => 12, 'title' => 'user_access'],
            ['id' => 13, 'title' => 'user_create'],
            ['id' => 14, 'title' => 'user_edit'],
            ['id' => 15, 'title' => 'user_view'],
            ['id' => 16, 'title' => 'user_delete'],
            ['id' => 22, 'title' => 'protocol_access'],
            ['id' => 23, 'title' => 'protocol_create'],
            ['id' => 24, 'title' => 'protocol_edit'],
            ['id' => 25, 'title' => 'protocol_view'],
            ['id' => 26, 'title' => 'protocol_delete'],
            ['id' => 32, 'title' => 'csi_access'],
            ['id' => 33, 'title' => 'csi_create'],
            ['id' => 34, 'title' => 'csi_edit'],
            ['id' => 35, 'title' => 'csi_view'],
            ['id' => 36, 'title' => 'csi_delete'],
            ['id' => 37, 'title' => 'channel_server_access'],
            ['id' => 38, 'title' => 'channel_server_create'],
            ['id' => 39, 'title' => 'channel_server_edit'],
            ['id' => 40, 'title' => 'channel_server_view'],
            ['id' => 41, 'title' => 'channel_server_delete'],
            ['id' => 42, 'title' => 'cso_access'],
            ['id' => 43, 'title' => 'cso_create'],
            ['id' => 44, 'title' => 'cso_edit'],
            ['id' => 45, 'title' => 'cso_view'],
            ['id' => 46, 'title' => 'cso_delete'],
            ['id' => 47, 'title' => 'channel_servers_area_access'],
            ['id' => 48, 'title' => 'sync_server_area_access'],
            ['id' => 49, 'title' => 'sync_server_access'],
            ['id' => 50, 'title' => 'sync_server_create'],
            ['id' => 51, 'title' => 'sync_server_edit'],
            ['id' => 52, 'title' => 'sync_server_view'],
            ['id' => 53, 'title' => 'sync_server_delete'],
            ['id' => 59, 'title' => 'configuration_setting_access'],
            ['id' => 60, 'title' => 'ftp_access'],
            ['id' => 61, 'title' => 'ftp_create'],
            ['id' => 62, 'title' => 'ftp_edit'],
            ['id' => 63, 'title' => 'ftp_view'],
            ['id' => 64, 'title' => 'ftp_delete'],
            ['id' => 65, 'title' => 'general_setting_access'],
            ['id' => 66, 'title' => 'general_setting_create'],
            ['id' => 67, 'title' => 'general_setting_edit'],
            ['id' => 68, 'title' => 'general_setting_view'],
            ['id' => 69, 'title' => 'general_setting_delete'],
            ['id' => 70, 'title' => 'output_setting_access'],
            ['id' => 71, 'title' => 'output_setting_create'],
            ['id' => 72, 'title' => 'output_setting_edit'],
            ['id' => 73, 'title' => 'output_setting_view'],
            ['id' => 74, 'title' => 'output_setting_delete'],
            ['id' => 75, 'title' => 'realtime_notification_access'],
            ['id' => 76, 'title' => 'realtime_notification_create'],
            ['id' => 77, 'title' => 'realtime_notification_edit'],
            ['id' => 78, 'title' => 'realtime_notification_view'],
            ['id' => 79, 'title' => 'realtime_notification_delete'],
            ['id' => 85, 'title' => 'report_setting_access'],
            ['id' => 86, 'title' => 'report_setting_create'],
            ['id' => 87, 'title' => 'report_setting_edit'],
            ['id' => 88, 'title' => 'report_setting_view'],
            ['id' => 89, 'title' => 'report_setting_delete'],
            ['id' => 90, 'title' => 'country_access'],
            ['id' => 91, 'title' => 'country_create'],
            ['id' => 92, 'title' => 'country_edit'],
            ['id' => 93, 'title' => 'country_view'],
            ['id' => 94, 'title' => 'country_delete'],
            ['id' => 95, 'title' => 'filter_access'],
            ['id' => 96, 'title' => 'filter_create'],
            ['id' => 97, 'title' => 'filter_edit'],
            ['id' => 98, 'title' => 'filter_view'],
            ['id' => 99, 'title' => 'filter_delete'],
            ['id' => 100, 'title' => 'cs_channel_list_access'],
            ['id' => 101, 'title' => 'cs_channel_list_create'],
            ['id' => 102, 'title' => 'cs_channel_list_edit'],
            ['id' => 103, 'title' => 'cs_channel_list_view'],
            ['id' => 104, 'title' => 'cs_channel_list_delete'],
            ['id' => 105, 'title' => 'video_server_type_access'],
            ['id' => 106, 'title' => 'video_server_type_create'],
            ['id' => 107, 'title' => 'video_server_type_edit'],
            ['id' => 108, 'title' => 'video_server_type_view'],
            ['id' => 109, 'title' => 'video_server_type_delete'],
            ['id' => 111, 'title' => 'config_default_access'],
            ['id' => 112, 'title' => 'timezone_access'],
            ['id' => 113, 'title' => 'timezone_create'],
            ['id' => 114, 'title' => 'timezone_edit'],
            ['id' => 115, 'title' => 'timezone_view'],
            ['id' => 116, 'title' => 'timezone_delete'],
            ['id' => 117, 'title' => 'video_setting_access'],
            ['id' => 118, 'title' => 'video_setting_create'],
            ['id' => 119, 'title' => 'video_setting_edit'],
            ['id' => 120, 'title' => 'video_setting_view'],
            ['id' => 121, 'title' => 'video_setting_delete'],
            ['id' => 128, 'title' => 'aggregation_server_setting_access'],
            ['id' => 129, 'title' => 'aggregation_server_access'],
            ['id' => 130, 'title' => 'aggregation_server_create'],
            ['id' => 131, 'title' => 'aggregation_server_edit'],
            ['id' => 132, 'title' => 'aggregation_server_view'],
            ['id' => 133, 'title' => 'aggregation_server_delete'],
            ['id' => 134, 'title' => 'baby_sync_server_access'],
            ['id' => 135, 'title' => 'baby_sync_server_create'],
            ['id' => 136, 'title' => 'baby_sync_server_edit'],
            ['id' => 137, 'title' => 'baby_sync_server_view'],
            ['id' => 138, 'title' => 'baby_sync_server_delete'],
            ['id' => 139, 'title' => 'video_server_access'],
            ['id' => 140, 'title' => 'clipdb_setting_access'],
            ['id' => 141, 'title' => 'clipdb_setting_create'],
            ['id' => 142, 'title' => 'clipdb_setting_edit'],
            ['id' => 143, 'title' => 'clipdb_setting_view'],
            ['id' => 144, 'title' => 'clipdb_setting_delete'],

        ];

        foreach ($items as $item) {
            \App\Permission::create($item);
        }
    }
}
